# azure-pipelines.yml
variables:
  - name: terraformFolder
    value: terraform
  - name: imageRepository
    value: azure-container-registry-name.azurecr.io
  - name: imageName
    value: react-app
  - name: imageTag
    value: $(Build.BuildId)
  
trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      architecture: 'x64'
  
  - task: TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: '1.1.4'

  - task: TerraformTaskV1@0
    displayName: Terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(terraformFolder)'
      
  - task: TerraformTaskV1@0
    displayName: Terraform validate
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(terraformFolder)'
      
  - task: TerraformTaskV1@0
    displayName: Terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'assessment'
      workingDirectory: '$(terraformFolder)'

  - task: TerraformTaskV1@0
    displayName: Terraform apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'assessment'
      workingDirectory: '$(terraformFolder)'
      args: '-auto-approve'

  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: '16.x'

  - script: |
      npm install
    displayName: Install app dependencies

  - script: |
      npm run test
    displayName: Test app

  - script: |
      npm run build
    displayName: Build app

  - task: Docker@2
    displayName: Build Docker image
    inputs:
      containerRegistry: $(azure-container-registry-name)
      repository: $(imageRepository)/$(imageName)
      command: build
      Dockerfile: $(System.DefaultWorkingDirectory)/Dockerfile
      tags: |
        $(imageTag)

  - task: Docker@2
    displayName: Push Docker image
    inputs:
      containerRegistry: $(azure-container-registry-name)
      repository: $(imageRepository)/$(imageName)
      command: push
      tags: |
        $(imageTag)
