# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  - name: terraformFolder
    value: terraform
  - name: service-connection
    value: assessment
  - name: ResourceGroupName
    value: oluseungrpnew
  - name: StorageAccountName
    value : oluwaseunstrrandiii
  - name: ContainerName
    value: oluwaseuncontainer
  - name: Location
    value: "eastus2"
    
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - terraform

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      architecture: 'x64'
  
  - task: Bash@3
    displayName: "Setup Terraform Backend"
    inputs:
      filePath: './terraform/create_backend.sh'
      arguments: '$(ResourceGroupName) $(StorageAccountName) $(Location) $(password)'
    
  
  - task: TerraformTaskV4@4
    displayName: "Initialize Terraform "
    inputs:
      provider: 'azurerm'
      workingDirectory: './$(terraformFolder)'
      command: 'init'
      backendServiceArm: $(service-connection)
      backendAzureRmResourceGroupName: $(ResourceGroupName)
      backendAzureRmContainerName: "tfstate"
      backendAzureRmKey: 'terraform.tfstate'
      backendAzureRmStorageAccountName: $(StorageAccountName)

  - task: TerraformTaskV4@4
    displayName: "Validate Terraform Configuration Files"
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: './$(terraformFolder)'

  - task: TerraformTaskV4@4
    displayName: "Terraform Plan"
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: './$(terraformFolder)'
      environmentServiceNameAzureRM: 'assessment'

  - task: TerraformTaskV4@4
    displayName: "Terraform Apply"
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: './$(terraformFolder)'
      commandOptions: '--auto-approve'
      environmentServiceNameAzureRM: 'assessment'
      

