# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: registryName 
    value: azure-container-registry-name.azurecr.io
  - name: imageName
    value: react-app
  - name: tag
    value: $(Build.BuildId)
  - name: Location
    value: "eastus2"
 
trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - terraform

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@4
  displayName: "Package and Test App"
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'myregistry'
    repository: '$(registryName)/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'src/main/java/Dockerfile'
    tags: |
      $(tag)
